- hosts: windows
  gather_facts: no
  tasks:
  - name: Check Comm
    win_ping:
  - name: Rename Computer
    win_shell: Rename-Computer -NewName "{{inventory_hostname}}" -Force
  - name: Enable Ping
    win_shell: Set-NetFirewallRule -Name FPS-ICMP4-ERQ-In -Enabled True;Set-NetFirewallRule -Name FPS-ICMP4-ERQ-out -Enabled True
  - name: Enable RDP Part 1
    win_shell: Set-ItemProperty ‘HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\‘ -Name “fDenyTSConnections” -Value 0
  - name: Enable RDP Part 2
    win_shell: Set-ItemProperty ‘HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\‘ -Name “UserAuthentication” -Value 1
  - name: Enable RDP Part 3
    win_shell: Enable-NetFirewallRule -DisplayGroup “Remote Desktop”
